'''title'''
__title__ = 'musicdl'
'''description'''
__description__ = 'A lightweight music downloader written by pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/musicdl'
'''version'''
__version__ = '2.2.2'